<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <!--PublishTrimmed>true</PublishTrimmed-->
        <!--PublishAot>true</PublishAot-->
        <!--PublishAotUsingRuntimePack>true</PublishAotUsingRuntimePack-->
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Xacor\Xacor.csproj"/>
    </ItemGroup>



</Project>
