name: Xacor

on:
  push:
    branches: [ master ]

jobs:
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.402
    - name: Build Xacor
      run: dotnet build --configuration Release
